id: P009377
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5171
  title: རྒྱུན་གྱི་ཞལ་འདོན་ཆོག་ཁྲིགས་གཏེར་གྱི་བུམ་བཟང་།
  author: ''
  volumes:
    8c70e5fbbab344fc8a8e6e431f2bd858:
      image_group_id: I3CN5173
      title: ''
      volume_number: 1
      total_pages: 288
      base_file: v001.txt
