id: I44D9DA8F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T06:07:12+00:00'
last_modified: '2022-06-08T10:34:52.464580+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5171
  title: རྒྱུན་གྱི་ཞལ་འདོན་ཆོག་ཁྲིགས་གཏེར་གྱི་བུམ་བཟང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F1C7:
      image_group_id: I3CN5173
      title: ''
      total_pages: 288
      order: 1
      base_file: F1C7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
